name    'get/removecontent'
version '2.0.10'
author  'GET-Automation'
license 'Apache2'
project_page 'https://github.comcast.com/GETAutomation/'
source 'https://github.comcast.com/GETAutomation/puppet-removecontent'
summary 'Puppet module for removecontent'
description 'This module installs and manages removecontent. Check README for details.'
dependency 'get/getlib'
